//! Build script: generates embedded.rs from plugins/ submodule.
//!
//! This is the SINGLE SOURCE OF TRUTH for plugin configs in the binary.
//! No manual gen_embedded.py, no manual copy, no version mismatch.
//!
//! Flow:
//!   1. cargo build triggers this build.rs
//!   2. Reads all plugin.toml and tags.scm from plugins/ submodule
//!   3. Generates src/analysis/plugin/embedded.rs
//!   4. Compiler includes the generated file
//!
//! To update plugins: git submodule update --remote && cargo build

use std::fs;
use std::path::Path;

fn main() {
    let plugins_dir = Path::new("../plugins");

    // If submodule not initialized, use existing embedded.rs
    if !plugins_dir.exists() || !plugins_dir.is_dir() {
        println!("cargo:warning=plugins/ submodule not found, using existing embedded.rs");
        return;
    }

    let mut entries: Vec<(String, String, String)> = Vec::new();

    let mut dirs: Vec<_> = fs::read_dir(plugins_dir)
        .expect("failed to read plugins/")
        .filter_map(|e| e.ok())
        .filter(|e| e.path().is_dir())
        .collect();
    dirs.sort_by_key(|e| e.file_name());

    for entry in &dirs {
        let name = entry.file_name().to_string_lossy().to_string();
        if name.starts_with('.') {
            continue;
        }
        let toml_path = entry.path().join("plugin.toml");
        if !toml_path.exists() {
            continue;
        }
        let toml_content = fs::read_to_string(&toml_path)
            .unwrap_or_else(|e| panic!("failed to read {}: {}", toml_path.display(), e));

        let scm_path = entry.path().join("queries").join("tags.scm");
        let scm_content = if scm_path.exists() {
            fs::read_to_string(&scm_path)
                .unwrap_or_else(|e| panic!("failed to read {}: {}", scm_path.display(), e))
        } else {
            String::new()
        };

        entries.push((name, toml_content, scm_content));
    }

    // Generate embedded.rs
    let out_path = Path::new("src/analysis/plugin/embedded.rs");
    let mut code = String::new();
    code.push_str("//! Auto-generated by build.rs from plugins/ submodule.\n");
    code.push_str("//! DO NOT EDIT MANUALLY — changes will be overwritten on next build.\n");
    code.push_str("//!\n");
    code.push_str(&format!("//! Generated from {} plugins.\n\n", entries.len()));
    code.push_str("/// (name, plugin_toml_content, tags_scm_content)\n");
    code.push_str("pub const EMBEDDED_PLUGINS: &[(&str, &str, &str)] = &[\n");

    for (name, toml, scm) in &entries {
        // Find safe raw string delimiter
        let td = find_safe_delim(toml);
        let sd = find_safe_delim(scm);
        code.push_str(&format!("    (\"{name}\",\n"));
        code.push_str(&format!("r{td}\"{toml}\"{td},\n"));
        code.push_str(&format!("r{sd}\"{scm}\"{sd}),\n"));
    }

    code.push_str("];\n");

    // Only write if content changed (avoids unnecessary recompilation)
    let existing = fs::read_to_string(out_path).unwrap_or_default();
    if existing != code {
        fs::write(out_path, &code)
            .unwrap_or_else(|e| panic!("failed to write {}: {}", out_path.display(), e));
        println!("cargo:warning=Generated embedded.rs with {} plugins", entries.len());
    }

    // Rerun if any plugin file changes
    println!("cargo:rerun-if-changed=../plugins");
    for entry in &dirs {
        let name = entry.file_name().to_string_lossy().to_string();
        println!("cargo:rerun-if-changed=../plugins/{}/plugin.toml", name);
        println!("cargo:rerun-if-changed=../plugins/{}/queries/tags.scm", name);
    }
}

/// Find minimum number of # for a safe raw string delimiter.
fn find_safe_delim(content: &str) -> String {
    let mut n = 1;
    loop {
        let hashes = "#".repeat(n);
        if !content.contains(&format!("\"{}", hashes)) && !content.contains(&format!("{}\"", hashes)) {
            return hashes;
        }
        n += 1;
    }
}
